### ISSUE TITLE
Fix base URLs.

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#146]
When tiled is served behind gunicorn and/or nginx, it provides the wrong base URL in the `links` it hands the client. Example:

```
$ http https://tiled-demo.blueskyproject.io/metadata/bmm | jq .data.links
{
  "self": "http://localhost:8000/metadata/bmm",
  "search": "http://localhost:8000/search/bmm"
}
```

Somehow we need to propagate the relevant information through. Off the top of my head, maybe this could involve...

* Grab it from the `Host` header (seems simplest if it is a general solution)
* Do something with `X-Forwarded-For`
* Extract something from the ASGI protocol

**Comment by dylanmcreynolds** [comment]
This is tricky.

I'm 90% sure that nginx will preserve the the client-sent `Host` header. 

I'm 90% sure that gunicorn will do the same.

Unfortunately, `Host` does not tell you the protocol being used. `https` should (but unfortunately can't) be assumed. This would also be counter to the intent of `Host`, which is really to let a single server host multiple domains and route requests to them.

`X-Forwarded-For` gives you the client's IP address. If there is something applicable from the world of `X-Forwarded-*`, I think it would be `X-Forwarded-Host` and `X-Forwarded-Proto`. These together would put together the root url.

So, I think we should think about `X-Forwarded-Proto` and `X-Forwarded-Host` as a way to put together the link URL. If they're not there, fall back on whatever is being used today.

It would be quite handy to have a config option that instructed tiled to print to the log the request headers for each request so that some future person could see what's actually happening in their unique deployment. I have used mitmproxy to do it sniff the http traffic, but it's not that straight forward, especially in complicated scenarios.
