### ISSUE TITLE
Better names for the *_indexer accessors

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#215]
Tiled client `Node` object satisfy the Python [`Mapping` interface](https://docs.python.org/3/library/collections.abc.html#collections.abc.Mapping); they are "dict-like". This is nice because all the things you can do with dicts

```py
d["my_data"]
len(d)
d.items()
# etc.
```

work on `Node` just the same.

The `Mapping` interface supports look up by _name_ like `d["my_data"]` but not look up by _position_ like `d[0]`. For `Node`, we want position-based access too; we want to support the Python [`Sequence` interface](https://docs.python.org/3/library/collections.abc.html#collections.abc.Sequence).

What are our options for doing this?

## Accessors with log names (current approach)

A `Node` _is_ a `Mapping` and it _has_ accessors that satisfy the `Sequence` interface.

```py
c.values_indexer[...]
c.keys_indexer[...]
c.items_indexer[...]
```

Pro:

* Explicit switching between named-based lookup and positional lookup
* Unambiguous

Con:

* Way too verbose to just get the first/last item

## Single Dispatch

```py
c[0]  # int -> Sequence-like access
c[:5]  # slice -> Sequence-like access
c["image"]  # str -> Mapping-like access
```

Pro:

* No new names to learn as the user

Cons:

* This kind of overloading can be confusing.
* Databroker has a _strong_ commitment to interpreting integer keys as `scan_id`. Breaking that would be a huge problem for Databroker. For this reason, this is a nonstarter.

## Overload `.values`, `.keys`, `.items`

Continue to support `.values()`, `.keys()`, `.items()`. _Also_ support `.values[]`, `.keys[]`, `.items[]`.

Pro:

* No new names to learn

Cons:

* Overloading interface methods like this with `__getitem__` is _very_ strange. (I can't think of a single time I've seen this done.)

## Give `.values_indexer` (the most common one) a shorter alias

Ideas for ideas include:

```
.s  # not obvious, but nice and short! meant to invoke "slice" or "sequence"
.slice
.seq  # for "sequence..."
.iloc  # familiar if you know pandas, but inscrutable otherwise
.val  # good name, but not obvious how to use it, or which is which between "val" and "values"
```

I really want a _very short_ way to type "Get me the first one," so I currently lean toward `.s`.

## Make `.values()`, `.keys()`, `.items()` return iterators that are indexable.

```py
c.values()[0]  # first
c.values()[:5]  # first 5
# ditto for keys, items
```

h/t @kleinhenz for this suggestion, which is very much in the spirit of [slicerator](https://github.com/soft-matter/slicerator) and [PIMS](https://github.com/soft-matter/pims). I can't believe I didn't think of it!

**Comment by tacaswell** [comment]
> Make .values(), .keys(), .items() return iterators that are indexable

This is my favorite.  Looks a bit funny, but at also means if you don `x = c.values()` it will still "do the right thing"

**Comment by maffettone** [comment]
In short, I agree with `c.values()[...]`. 

I went digging and it turns out this has been a contentious topic previously w.r.t. dictionaries. 


Python 2 used the notion `dic.items()[0]`, but this changed in 3.X when these dictionary methods starting returning views (i.e. references/pointers of sort).  [So there is precedent for this](https://stackoverflow.com/questions/10058140/accessing-items-in-an-collections-ordereddict-by-index). 

I'm not sure how the implementaiton would look since these are currently producing generators,  but I'm sure there's a plan. 
https://github.com/bluesky/tiled/blob/54b26842d1926b451ac6ecd45dd94208bde40f24/tiled/client/node.py#L374-L401

There is [some discussion (and plenty of sass) ](https://mail.python.org/archives/list/python-ideas@python.org/thread/S7UMTWK65X6BJDYZ3SSU7I7HOIASDMMJ/)over the efficiency concerns here. But since this isn't a class in the standard library, and we need to meet users where they are, it's probably best to use this for inspiration on implementation. 
One notion that came from this discussion that I do like---and find more elegant than `c[-1]`---is `.first()`, `.last()`,  `.head()`, and `.tail()` as simple slicing methods. But depending on the outcomes, those could just be short aliases.

**Comment by danielballan** [comment]
Great find!

For a generic iterator, positional lookup raises performance concerns. (To get the Nth item you may need to iterate through the first N.) In our case, our implementation happens to support random access, and for that reason I think the efficiency concerns do not apply.

I agree that `.first()`, `.last()`, `.head()`, and `.tail()` would be very nice. Yes, we can implement them as aliases.
