### ISSUE TITLE
How to specify mimetype for file with no extension?

### ISSUE THREAD

**Issue by prjemian** [bluesky/tiled#315]
```py
/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/tiled/adapters/files.py:707: UserWarning: The file at ../../NeXus/exampledata/APS/scan2nexus/README has some type that is not recognized. The file will be skipped. Pass in a mimetype for this file extension via the parameter DirectoryAdapter.from_directory(..., mimetypes_by_file_ext={...}) or a function for determining the mimetype based the full filepath DirectoryAdapter.from_directory(..., mimetype_detection_hook=func).
```

**Comment by prjemian** [comment]
File is `README`.  One way is to intercept in `custom:detect_mimetype` and assign a mimetype such as `text/x-readme`.

**Comment by prjemian** [comment]
Such as in [`tiled-demo/custom:detect_mimetype`](https://github.com/prjemian/tiled-demo/blob/e0afc46db2f313c2e28bc42b4f33b2705a52e034/custom.py#L54-L55):

```py
    if filename.name == "README":
        mimetype = "text/readme"
```

**Comment by danielballan** [comment]
To the general question of detecting a file with no extension: yes, this is a good use of `detect_minetype` since we need to consider the full name (or in other potential examples, the full path or the file’s content).

To this specific example: since Tiled cannot do anything with text data, it seems like what we want Tiled to do with this file is ignore it. We don’t want it to try to parse it like a text file of numbers.

Or maybe we want Tiled to put this text in metadata on the node that corresponds to the directory containing it?

**Comment by dylanmcreynolds** [comment]
To be super picky, in the formal world of media-types, `text/readme`should probably be `text/x.readme`. There is no formal registered mime-type for [readme](https://www.iana.org/assignments/media-types/media-types.xhtml). Adding the `x.` prefix declares that you're using an unregistered type. Would this matter in the real world? Probably not.

**Comment by prjemian** [comment]
`x.readme` or `x-readme`?  Isn't the `-` delimiter the one to pick?  Where's the authority on that one?  Perhaps we follow the pattern described in the examples for [gcode](https://mimetype.io/all-types/#gcode).  Loose standard.

**Comment by danielballan** [comment]
I thought it was `x-`, and I convey that somewhere in the Tiled documentation, but it looks like `x.` is now more standard. https://en.wikipedia.org/wiki/Media_type#Unregistered_tree Thrilling reading!

I would actually argue that the right MIME type here is `text/plain`. The MIME type conveys the _format_ ("plain text") not the content ("a README file"). A given user portal, like a web browser, only needs to know the format in order to present it to the user.

All of this is a little bit moot because of course we just want Tiled to _ignore_ this file, one way or another, because it is not numerical data.

**Comment by prjemian** [comment]
In my particular case, `text/plain` seemed obvious but I wanted to signal a bespoke handler, thus the custom mimetype.

FWIW: a bit of investigating with one of my Linux workstations: shows that `/x.` does not appear in any `mime.type` file.  OTOH, `/x-` appears hundreds of times amongst the 9 files searched:

```bash
(bluesky_2022_3) prjemian@zap:~/.../bluesky_training/bluesky$ locate mime.type | wc -l
9
(bluesky_2022_3) prjemian@zap:~/.../bluesky_training/bluesky$ grep "/x\." $(locate mime.type) | wc -l
0
(bluesky_2022_3) prjemian@zap:~/.../bluesky_training/bluesky$ grep "/x-" $(locate mime.type) | wc -l
422
```

**Comment by danielballan** [comment]
I suspect the attempt to move to `x.` is an example of a standards body trying to change something (modernize it, perhaps) after the horse is long out of the barn.

**Comment by prjemian** [comment]
Thanks, all, for the discussion.  The takeaway answer is to use a custom `detect_mimetype ()` handler and intercept the file(s), making mimetype assignments as deemed appropriate.  No code changes to tiled are expected from this issue.
