### ISSUE TITLE
Can't slice (with predicate push-down) a field within a field of an Awkward Array

### ISSUE THREAD

**Issue by jpivarski** [bluesky/tiled#578]
We get `KeyError: 'nodeX-offsets'` issues (for different `X`, depending on the attempted slice).

I should make a suite of examples to test and go through them with a persistent database that I can reboot, make changes to the code, and try again, to narrow down on this error. Maybe that can become a unit test.

I don't know why, but it's only showing me the part of the stack trace in which Awkward fails to find the key in the `container`. It's not showing me the Tiled server code that calls Awkward, where I want to look and see which keys it _does_ have.

The types of slices that are failing:

```python
client["dataset_name"]["file", "filename"]
```

where `"filename"` is a field of a record that is inside the `"file"` field of an outer record.

**Comment by danielballan** [comment]
> Maybe that can become a unit test.

That would be great. A parameterized test that checks for round-tripping a good variety of awkward structures is much needed.

> It's not showing me the Tiled server code that calls Awkward

Is the server running in a separate process, via `tiled serve catalog --temp` or similar? We can run the server and client in the same process, passing messages via Python function calls instead of network calls. I have been debating whether to make a convenience function for this, and if so how to parameterize and name it. For now, this should work, with apologies for the verbosity:

```py
import tempfile
from tiled.catalog import in_memory
from tiled.server.app import build_app
from tiled.client import Context, from_context

# Build an app equivalent to `tiled serve catalog --temp`
tmpdir = tempfile.TemporaryDirectory()
catalog = in_memory(writable_storage=tmpdir.name)
app = build_app(catalog)

# Run the app event loop on a background thread.
context = Context.from_app(app)
c = from_context(context)

# Upload an array and access a slice.
import awkward as ak
array = ak.Array({"file": {"filename": [1,2,3]}})
c.write_awkward(array, key="dataset_name")
c["dataset_name"]["file", "filename"]
```

> The types of slices that are failing

This works for me on `main`:

```py
array = ak.Array({"file": {"filename": [1,2,3]}})
c.write_awkward(array, key="dataset_name")
c["dataset_name"]["file", "filename"]
```

so I think I have probably not constructed a sufficient example here. If you share one I'd be happy to dig deeper on both this specific issue and the debugging workflow in general.

**Comment by jpivarski** [comment]
That makes sense: I was using `tiled serve catalog --temp` as a separate process; doing this in a single process should make it easier to get stack traces. I wonder, though, why I saw any stack trace messages from the server (the ones from Awkward's slice-handling)?

I'm putting this issue in my to-do list, so that I remember to do this testing.

**Comment by danielballan** [comment]
Thanks.

My best guess is that you were seeing the slice-handling applied to the typetracer, as we work out client side which form keys are touched by the slice.
