### ISSUE TITLE
Integrate with ORCID

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#76]
This may be a good early example for three-legged auth.

Start here: https://info.orcid.org/documentation/integration-guide/registering-a-public-api-client/

**Comment by dylanmcreynolds** [comment]
When I integrated with ORCID in a full OIDC integration, there were a couple of things I ran into.

For me, I started down the path of getting an API key, which I didn't need to do. Looks like you're on the right path with that link above. it's  a little confusing, but if you're just doing authentication, you don't need to go through their process of setting up a sandbox account and demoing your configuration to them. You can just use their "Public API", confusing, because there's a great deal about their API that is public, but here they just mean "the API for authentication". Anything beyond that, like read or writing to people's ORCID records, needs the human approval process.

There's some other strangeness about getting profile information in an OIDC integration. I could go look it up, but there's a little info here (from a javascript project) https://gist.github.com/JanKoppe/1491e37d1022c77a286087e6c81d6092 and I had found that I could only send these scopes `["openid", "/authenticate"]`. I could never get `profile` to work.

**Comment by danielballan** [comment]
Closed by #87
